openapi: 3.1.0
info:
  title: test title
  description: test description
  version: 1.0.0
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
servers:
  - url: /
paths:
  /api/v1/resources:
    get:
      tags:
        - Resources
      summary: List all resources
      operationId: listResources
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
                  type: object
                  properties:
                    created_at:
                      $ref: '#/components/schemas/Time'
                      type: object
                    name:
                      type: string
                    resource_id:
                      type: integer
                    tenant_id:
                      type: integer
                    type:
                      type: string
                  required:
                    - tenant_id
                    - resource_id
                    - name
                    - type
                    - created_at
              example: []
        "404":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
  /api/v1/resources/{resourceId}:
    get:
      tags:
        - Resources
      operationId: getResource
      parameters:
        - name: resourceId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/rtype'
            type: object
          example: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
                type: object
                properties:
                  created_at:
                    $ref: '#/components/schemas/Time'
                    type: object
                  name:
                    type: string
                  resource_id:
                    type: integer
                  tenant_id:
                    type: integer
                  type:
                    type: string
                required:
                  - tenant_id
                  - resource_id
                  - name
                  - type
                  - created_at
              example:
                tenantid: 0
                resourceid: 0
                name: ""
                type: ""
                createdat: 0001-01-01T00:00:00Z
        "404":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
    head:
      tags:
        - Resources
      operationId: checkResourceExists
      parameters:
        - name: resourceId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/rtype'
            type: object
          example: {}
      responses:
        "204":
          description: ""
        "404":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
  /api/v1/tenants:
    get:
      tags:
        - Tenants
      summary: List all tenants
      operationId: listTenants
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tenant'
                  type: object
                  properties:
                    created_at:
                      $ref: '#/components/schemas/Time'
                      type: object
                    name:
                      type: string
                    plan:
                      type: string
                    tenant_id:
                      type: integer
                  required:
                    - tenant_id
                    - name
                    - plan
                    - created_at
              example: []
        "404":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
    post:
      tags:
        - Tenants
      operationId: createTenant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tenant'
              type: object
              properties:
                created_at:
                  $ref: '#/components/schemas/Time'
                  type: object
                name:
                  type: string
                plan:
                  type: string
                tenant_id:
                  type: integer
              required:
                - tenant_id
                - name
                - plan
                - created_at
            example:
              tenantid: 0
              name: ""
              plan: ""
              createdat: 0001-01-01T00:00:00Z
        required: true
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
                type: object
                properties:
                  created_at:
                    $ref: '#/components/schemas/Time'
                    type: object
                  name:
                    type: string
                  plan:
                    type: string
                  tenant_id:
                    type: integer
                required:
                  - tenant_id
                  - name
                  - plan
                  - created_at
              example:
                tenantid: 0
                name: ""
                plan: ""
                createdat: 0001-01-01T00:00:00Z
        "400":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
  /api/v1/tenants/{tenantID}:
    get:
      tags:
        - Tenants
      operationId: getTenant
      parameters:
        - name: tenantID
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/rtype'
            type: object
          example: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
                type: object
                properties:
                  created_at:
                    $ref: '#/components/schemas/Time'
                    type: object
                  name:
                    type: string
                  plan:
                    type: string
                  tenant_id:
                    type: integer
                required:
                  - tenant_id
                  - name
                  - plan
                  - created_at
              example:
                tenantid: 0
                name: ""
                plan: ""
                createdat: 0001-01-01T00:00:00Z
        "404":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
    put:
      tags:
        - Tenants
      operationId: updateTenant
      parameters:
        - name: tenantID
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/rtype'
            type: object
          example: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tenant'
              type: object
              properties:
                created_at:
                  $ref: '#/components/schemas/Time'
                  type: object
                name:
                  type: string
                plan:
                  type: string
                tenant_id:
                  type: integer
              required:
                - tenant_id
                - name
                - plan
                - created_at
            example:
              tenantid: 0
              name: ""
              plan: ""
              createdat: 0001-01-01T00:00:00Z
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
                type: object
                properties:
                  created_at:
                    $ref: '#/components/schemas/Time'
                    type: object
                  name:
                    type: string
                  plan:
                    type: string
                  tenant_id:
                    type: integer
                required:
                  - tenant_id
                  - name
                  - plan
                  - created_at
              example:
                tenantid: 0
                name: ""
                plan: ""
                createdat: 0001-01-01T00:00:00Z
        "400":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
    delete:
      tags:
        - Tenants
      operationId: deleteTenant
      parameters:
        - name: tenantID
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/rtype'
            type: object
          example: {}
      responses:
        "204":
          description: ""
        "404":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
    head:
      tags:
        - Tenants
      operationId: checkTenantExists
      parameters:
        - name: tenantID
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/rtype'
            type: object
          example: {}
      responses:
        "204":
          description: ""
        "404":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
  /api/v1/tenants/{tenantID}/resources:
    get:
      tags:
        - Tenants
        - Resources
      operationId: listTenantResources
      parameters:
        - name: tenantID
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/rtype'
            type: object
          example: {}
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
                  type: object
                  properties:
                    created_at:
                      $ref: '#/components/schemas/Time'
                      type: object
                    name:
                      type: string
                    resource_id:
                      type: integer
                    tenant_id:
                      type: integer
                    type:
                      type: string
                  required:
                    - tenant_id
                    - resource_id
                    - name
                    - type
                    - created_at
              example: []
        "404":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
    post:
      tags:
        - Tenants
        - Resources
      operationId: createTenantResource
      parameters:
        - name: tenantID
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/rtype'
            type: object
          example: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
              type: object
              properties:
                created_at:
                  $ref: '#/components/schemas/Time'
                  type: object
                name:
                  type: string
                resource_id:
                  type: integer
                tenant_id:
                  type: integer
                type:
                  type: string
              required:
                - tenant_id
                - resource_id
                - name
                - type
                - created_at
            example:
              tenantid: 0
              resourceid: 0
              name: ""
              type: ""
              createdat: 0001-01-01T00:00:00Z
        required: true
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
                type: object
                properties:
                  created_at:
                    $ref: '#/components/schemas/Time'
                    type: object
                  name:
                    type: string
                  resource_id:
                    type: integer
                  tenant_id:
                    type: integer
                  type:
                    type: string
                required:
                  - tenant_id
                  - resource_id
                  - name
                  - type
                  - created_at
              example:
                tenantid: 0
                resourceid: 0
                name: ""
                type: ""
                createdat: 0001-01-01T00:00:00Z
        "400":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
                type: object
                properties:
                  detail:
                    type: string
                  instance:
                    type: string
                  status:
                    type: integer
                  title:
                    type: string
                  type:
                    type: string
                required:
                  - type
                  - title
                  - status
                  - detail
              example:
                type: ""
                title: ""
                status: 0
                detail: ""
                instance: null
components: {}
